FROM lscr.io/linuxserver/webtop:ubuntu-xfce

# Cambiamos apk por apt-get
# Actualizamos repositorios e instalamos XCA y herramientas
RUN apt-get update && \
    apt-get install -y xca openssl curl nano mousepad && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Título de la pestaña
ENV TITLE="Attacker Workstation (XCA)"